[package]
name = "wfpi"
version = "0.1.0"
authors = ["Alic Szecsei <alszecse@microsoft.com>"]
edition = "2018"

[dependencies]
rppal = "0.11.3"
simple-signal = "1.1.1"
failure = "0.1.5"

[profile.dev]
panic = "abort"
opt-level = 3

[profile.release]
panic = "abort"
